UPDATE terms SET terms.term_caller = 'marrital:single' WHERE terms.term_caller = 'marital-status:single';
UPDATE terms SET terms.term_caller = 'marrital:married' WHERE terms.term_caller = 'marital-status:married';
UPDATE terms SET terms.term_caller = 'graduation:illiterate' WHERE terms.term_caller = 'graduation-status:illiterate';
UPDATE terms SET terms.term_caller = 'graduation:undergraduate' WHERE terms.term_caller = 'graduation-status:undergraduate';
UPDATE terms SET terms.term_caller = 'graduation:graduate' WHERE terms.term_caller = 'graduation-status:graduate';
UPDATE terms SET terms.term_caller = 'employmentstatus:employee' WHERE terms.term_caller = 'employement-status:employed';
UPDATE terms SET terms.term_caller = 'employmentstatus:unemployed' WHERE terms.term_caller = 'employement-status:unemployed';
UPDATE terms SET terms.term_caller = 'employmentstatus:retired' WHERE terms.term_caller = 'employement-status:retired';
UPDATE terms SET terms.term_caller = 'degree:under diploma' WHERE terms.term_caller = 'degree:under-diploma';
UPDATE terms SET terms.term_caller = 'degree:diploma' WHERE terms.term_caller = 'degree:diploma';
UPDATE terms SET terms.term_caller = 'degree:2 year college' WHERE terms.term_caller = 'degree:associate-degree';
UPDATE terms SET terms.term_caller = 'degree:bachelor' WHERE terms.term_caller = 'degree:bachelors-degree';
UPDATE terms SET terms.term_caller = 'degree:master' WHERE terms.term_caller = 'degree:masters-degree';
UPDATE terms SET terms.term_caller = 'degree:phd' WHERE terms.term_caller = 'degree:doctorate';
UPDATE terms SET terms.term_caller = 'range:-13' WHERE terms.term_caller = 'age-range:under-13';
UPDATE terms SET terms.term_caller = 'range:14-17' WHERE terms.term_caller = 'age-range:14-17';
UPDATE terms SET terms.term_caller = 'range:18-24' WHERE terms.term_caller = 'age-range:18-24';
UPDATE terms SET terms.term_caller = 'range:25-30' WHERE terms.term_caller = 'age-range:25-30';
UPDATE terms SET terms.term_caller = 'range:31-44' WHERE terms.term_caller = 'age-range:31-44';
UPDATE terms SET terms.term_caller = 'range:45-59' WHERE terms.term_caller = 'age-range:45-59';
UPDATE terms SET terms.term_caller = 'range:60+' WHERE terms.term_caller = 'age-range:above-60';
UPDATE terms SET terms.term_caller = 'degree:bachelor' WHERE terms.term_caller = 'degree:bachelor-degree';
UPDATE terms SET term_title = 'other' WHERE term_caller = 'lifestyle:food:beverage:type:other' AND term_title = 'reza mohiti' LIMIT 1;