CREATE TABLE IF NOT EXISTS `pollopts` (
`id` 			bigint(20) 	unsigned NOT NULL AUTO_INCREMENT,
`post_id` 		bigint(20) 	unsigned NOT NULL,
`key`           smallint(3) unsigned NULL,
`text`			varchar(700) NULL,
`subtype`		varchar(200) NULL,
`true` 			bit(1) NULL DEFAULT 0,
`groupscore`    varchar(50) NULL DEFAULT NULL,
`score` 		smallint(5) NULL DEFAULT NULL,
`attachment_id`	bigint(20) unsigned NULL,
`attachmenttype` ENUM('image','audio','video','pdf','other') NULL,
`profile`       varchar(200) NULL DEFAULT NULL,
`desc`			text NULL DEFAULT NULL,
`meta`			text NULL DEFAULT NULL,
`status`        ENUM('enable','disable','expired','awaiting','filtered','blocked','spam') NOT NULL DEFAULT 'enable',
`createdate` 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`datemodified` 	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
UNIQUE KEY `unique` (`post_id`, `key`) USING BTREE,
CONSTRAINT `pollopt_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;